[package]
name = "glium"
version = "0.6.7"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = """
Elegant and safe OpenGL wrapper.

Glium is an intermediate layer between OpenGL and your application. You still need to manually handle
the graphics pipeline, but without having to use OpenGL's old and error-prone API.

Its objectives:
 - Be safe to use. Many aspects of OpenGL that can trigger a crash if misused are automatically handled by glium.
 - Provide an API that enforces good pratices such as RAII or stateless function calls.
 - Be compatible with all OpenGL versions that support shaders, providing unified API when things diverge.
 - Avoid all OpenGL errors beforehand.
 - Produce optimized OpenGL function calls, and allow the user to easily use modern OpenGL techniques.
"""
keywords = ["opengl", "gamedev"]
documentation = "http://tomaka.github.io/glium/glium/index.html"
homepage = "http://tomaka.github.io/glium"
repository = "https://github.com/tomaka/glium"
license = "Apache-2.0"
build = "build/main.rs"
exclude = ["doc", ".travis.yml", "circle.yml"]

[features]
default = ["glutin", "image", "nalgebra", "cgmath", "gl_read_buffer", "gl_depth_textures"]
gl_read_buffer = []
gl_uniform_blocks = []
gl_sync = []
gl_program_binary = []
gl_tessellation = []
gl_instancing = []
gl_integral_textures = []
gl_depth_textures = []
gl_stencil_textures = []
gl_texture_1d = []
gl_texture_3d = []
gl_texture_multisample = []
gl_texture_multisample_array = []
gl_bindless_textures = []
headless = []

[dependencies.glutin]
version = "0.2.0"
features = ["window"]
optional = true

[dependencies.cgmath]
version = "0.2.0"
optional = true

[dependencies.nalgebra]
version = "0.2.14"
optional = true

[dependencies.image]
version = "0.3.9"
optional = true

[dependencies]
lazy_static = "0.1"
gl_common = "0.0.4"
libc = "0.1"
smallvec = "0.1.5"

[build-dependencies]
gl_generator = "0.0.27"
khronos_api = "0.0.7"

[dev-dependencies]
clock_ticks = "0.0.5"
genmesh = "0.2.1"
obj = "0.2.1"
rand = "0.3"
